---
# tasks file for rnkoaa.ufw
- name: install ufw
  apt: pkg=ufw state=present

- name: disable and reset firewall
  ufw: state=reset

- name: open firewall for ssh
  ufw: rule=allow name=OpenSSH

- name: open firewall on specific ports
  ufw: rule=allow port={{ item }}
  with_items: "{{ ufw_open_ports }}"

- name: reload and enable firewall
  ufw: state=enabled policy=deny
