---
# tasks file for rnkoaa.base ubuntu version

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

# - name: Install pip
#   apt:
#     name: 'python-pip'
#     state: present
#   become: true

- name: Install pip3
  apt:
    name: 'python3-pip'
    state: present
  become: true