---
- hosts: "{{ m_host | default('all') }}"
  gather_facts: false
  become: true
  tasks:
    - group:
        name: vault
        state: present

    - user:
        name: vault
        comment: "Vault user"
        group: vault

    - file:
        path: /vault/config
        state: directory
        owner: vault
        recurse: yes
        group: root
        mode: 0755

    - template:
        src: templates/config.hcl.j2
        dest: /vault/config/config.hcl
        owner: vault
        group: vault
        mode: 0644
      become: true

    - name: create vault container
      docker_container:
        name: vault
        image: vault
        state: started
        command: server
        ports:
          - "8200:8200"
        capabilities:
          - IPC_LOCK
        volumes:
          - /vault/config:/vault/config
        networks:
          - name: "{{ hashi_stack_network_name }}"
