---
- hosts: "{{ m_host | default('all') }}"
  gather_facts: false
  become: true
  tasks:
    - group:
        name: nomad
        state: present

    - user:
        name: nomad
        comment: "Nomad user"
        group: nomad

    - file:
        path: /nomad/config
        state: directory
        owner: nomad
        recurse: yes
        group: root
        mode: 0755

    - template:
        src: templates/config.json.j2
        dest: /nomad/config/config.json
        owner: nomad
        group: nomad
        mode: 0644
      become: true

    - name: create nomad container
      docker_container:
        name: nomad
        image: rnkoaa/nomad:0.7.1
        state: started
        command: server
        restart: yes
        ports:
          - "8200:8200"
        capabilities:
          - IPC_LOCK
        volumes:
          - /nomad/config:/nomad/config
        networks:
          - name: "{{ hashi_stack_network_name }}"
