---
- hosts: "{{ m_host | default('all') }}"
  gather_facts: false
  vars:
    - server_ip: "{{ hostvars[inventory_hostname].ext_ip }}"
    - server_node_ip: "{{ }}"
    - consul_node_name: consul
    - consul_port: 8500
    - datacenter_name: alpha
    - node_name: "{{ ansible_hostname }}"
    - nomad_server_ips: []
    - other_nomad_servers: []
  become: true

  pre_tasks:
    - name: Build a list of all the nomad servers for joining cluster
      set_fact:
        nomad_server_ips: "{{ nomad_server_ips }} + [ '{{ hostvars[item].ext_ip }}' ]"
      with_items: "{{ groups['all'] }}"

    - name: Remove current node ip from list of joining addresses
      set_fact:
        other_nomad_servers: "{{ nomad_server_ips | reject('search',server_ip) | list }}"

  tasks:
    - group:
        name: nomad
        state: present

    - user:
        name: nomad
        comment: "Nomad user"
        group: nomad

    - file:
        path: /nomad/config
        state: directory
        owner: nomad
        recurse: yes
        group: root
        mode: 0755
    - file:
        path: /nomad/data
        state: directory
        owner: nomad
        recurse: yes
        group: root
        mode: 0755

    - template:
        src: templates/nomad.config.json.j2
        dest: /nomad/config/config.json
        owner: nomad
        group: nomad
        mode: 0644
      become: true

    - name: create nomad container
      docker_container:
        name: nomad
        image: rnkoaa/nomad:0.7.1
        state: started
        command: agent -config /nomad/config/config.json
        restart: yes
        ports:
          - "4646:4646"
          - "4648:4648"
          - "4649:4649"
        capabilities:
          - IPC_LOCK
        volumes:
          - /nomad/config:/nomad/config
          - /nomad/data:/nomad/data
        networks:
          - name: "{{ hashi_stack_network_name }}"
