---
# tasks file for rnkoaa.base
  
- name: Install docker dependencies
  vars:
    docker_apps:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_apps }}"
  become: true

- name: Add repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  become: true

- name: Install docker
  yum:
    name: docker-ce
    state: present
  notify: start-docker
  become: true
